spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql:  false
  datasource:
    url: jdbc:postgresql://localhost:5432/G&A.BoardGames
    username: postgres
    password: root
  flyway:
    baseline-on-migrate: true

